version: '3.1'

services:

  wordpress:
    container_name: rollbar-php-wordpress_wordpress
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - rollbar-php-wordpress_wordpress:/var/www/html
      - ./../:/var/www/html/wp-content/plugins/rollbar

  db:
    container_name: rollbar-php-wordpress_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - rollbar-php-wordpress_db:/var/lib/mysql

volumes:
  rollbar-php-wordpress_wordpress:
  rollbar-php-wordpress_db: